version: "3.7"
services:
  phpstan:
    image: phpstan/phpstan:0.11.19
    volumes:
      - .:/app
    entrypoint: phpstan analyse -c phpstan.neon
    init: true

  test:
    image: phpstan/phpstan:0.11.19
    volumes:
      - .:/app
    entrypoint: vendor/bin/phpunit tests
    init: true
